framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

when@prod:
    framework:
        assets:
            json_manifest_path: '%kernel.project_dir%/public/assets/manifest.json'
