twig:
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/templates/english': english
        '%kernel.project_dir%/templates/french': french
        '%kernel.project_dir%/templates/russian': russian
        '%kernel.project_dir%/templates/ukrainian': ukrainian
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        ga_tracking_id: '%env(GA_TRACKING_ID)%'
