services:
  web:
    image: trompette/interpretation:buster
    container_name: "interpretation-web"
    hostname: "interpretation"
    domainname: "merlet.biz"
    ports: ["8080:8080"]
    volumes: [".:/srv"]
  composer:
    image: composer:2
    container_name: "interpretation-composer"
    user: "${UID}:${GID}"
    working_dir: "/srv"
    volumes: [".:/srv"]
  node:
    image: node
    container_name: "interpretation-node"
    user: "${UID}:${GID}"
    working_dir: "/srv"
    volumes: [".:/srv"]
