version: '3.8'
services:
  web:
    build: .
    container_name: "interpretation-web"
    hostname: "interpretation"
    domainname: "merlet.biz"
    ports: ["8080:8080"]
    volumes: [".:/srv"]
  composer:
    image: composer:2
    container_name: "interpretation-composer"
    working_dir: "/srv"
    volumes: [".:/srv"]
  node:
    image: node
    container_name: "interpretation-node"
    working_dir: "/srv"
    volumes: [".:/srv"]
