services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Sveta\:
        resource: '../src/Sveta/*'

    Sveta\Controller\:
        resource: '../src/Sveta/Controller'
        tags: ['controller.service_arguments']
