name: "Automated Tests"

on:
  push:
    branches: 
      - "master"
  pull_request:
    branches: 
      - "master"

jobs:
  smoke-tests:
    name: "Smoke tests"
    runs-on: "ubuntu-latest"

    steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"

    - name: "Start environment"
      run: "make up"

    - name: "Install dependencies"
      run: "make install"

    - name: "Run test suite"
      run: "make test"

    - name: "Stop environment"
      run: "make down"
